// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Author: wallmasterr (https://sketchfab.com/wallmasterr)
// License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
// Source: https://sketchfab.com/3d-models/tenhun-falling-spaceman-fanart-9fd80b6a259f41fd99e6f56eee686dc5
// Title: Tenhun Falling spaceman (FanArt)
// */


// import React, { useEffect, useRef } from "react";
// import { useGLTF, useAnimations } from "@react-three/drei";
// import { useFrame } from "@react-three/fiber";
// import { useMotionValue, useSpring } from "motion/react";

// const MODEL_URL = `${import.meta.env.BASE_URL}models/portrait.glb`;

// export function Astronaut(props) {
//   const group = useRef();

//   const { nodes, materials, animations } = useGLTF(MODEL_URL);
//   const { actions } = useAnimations(animations, group);

//   /* ▶ Play animation safely */
//   useEffect(() => {
//     if (!animations?.length || !actions) return;
//     const firstAnim = animations[0]?.name;
//     actions[firstAnim]?.reset().fadeIn(0.5).play();
//   }, [actions, animations]);

//   /* ⬆ Floating motion */
//   const y = useMotionValue(5);
//   const ySpring = useSpring(y, { damping: 30 });

//   useEffect(() => {
//     ySpring.set(-1);
//   }, [ySpring]);

//   useFrame(() => {
//     if (!group.current) return;
//     group.current.position.y = ySpring.get();
//   });

//   return (
//     <group
//       ref={group}
//       dispose={null}
//       rotation={[-Math.PI / 2, -0.2, 2.2]}
//       scale={props.scale ?? 0.3}
//       position={props.position ?? [1.3, -1, 0]}
//       {...props}
//     >
//       <group name="Sketchfab_Scene">
//         <group name="Sketchfab_model">
//           <group name="Root">
//             <group name="metarig">
//               <primitive object={nodes.metarig_rootJoint} />

//               {[
//                 "Cube001_0",
//                 "Cube005_0",
//                 "Cube002_0",
//                 "Plane_0",
//                 "Cube008_0",
//                 "Cube004_0",
//                 "Cube003_0",
//                 "Cube_0",
//                 "Cube009_0",
//                 "Cube011_0",
//               ].map((name) => (
//                 <skinnedMesh
//                   key={name}
//                   geometry={nodes[name].geometry}
//                   material={materials["AstronautFallingTexture.png"]}
//                   skeleton={nodes[name].skeleton}
//                 />
//               ))}
//             </group>
//           </group>
//         </group>
//       </group>
//     </group>
//   );
// }

// /* ✅ Correct preload (ONLY ONCE) */
// useGLTF.preload(MODEL_URL);


/*
3D Portrait Component
(Replaces astronaut with your own portrait)
*/import { useGLTF, useAnimations } from "@react-three/drei";
import { useEffect, useRef } from "react";
import { Box3, Vector3 } from "three";
import { useFrame } from "@react-three/fiber";


const MODEL_URL = "/models/portrait.glb";

export function Astronaut({
  position = [0.2, -1, 0],     // ⭐ ONLY control Y here
  rotation = [0, Math.PI, 0], // face camera
}) {
  const group = useRef();
  const model = useRef();

  const { scene, animations } = useGLTF(MODEL_URL);
  const { actions } = useAnimations(animations, group);

  /* ▶ PLAY IDLE ANIMATION */
  useEffect(() => {
    if (!animations.length || !actions) return;

    const name = animations[0].name;
    actions[name]?.reset().fadeIn(0.4).play();

    return () => actions[name]?.fadeOut(0.3);
  }, [actions, animations]);

  /* 🔥 CENTER + SCALE MODEL (NOT GROUP) */
  useEffect(() => {
    if (!model.current) return;

    const box = new Box3().setFromObject(model.current);
    const center = box.getCenter(new Vector3());
    model.current.position.sub(center);

    const size = box.getSize(new Vector3()).length();
    const scale = 1.6 / size; // ⭐ CHANGE THIS ONLY for size
    model.current.scale.setScalar(scale);
  }, []);

  useFrame(() => {
  if (!group.current) return;
  group.current.position.y = position[1];
});


  return (
    <group
      ref={group}
      position={position}   // ⭐ THIS CONTROLS Y (SAFE)
      rotation={rotation}
    >
      <primitive ref={model} object={scene} />
    </group>
  );
}

useGLTF.preload(MODEL_URL);
